function params = default_params()
% Returns a network parameter structure initialised with default values.

    params = struct('nsteps', 10, ...
        'stddev', .01, ...
        'momentum', .9, ...
        'initialrate', .005, ...
        'ratedecay', 1, ...
        'adjust_rate', true, ...
        'batchsize', 500, ...
        'early_stopping', false);

end

